### ISSUE TITLE
More flexibility in gap_assembly

### ISSUE THREAD

**Issue by kfuku52** [maedat/GFF2MSS#18]
I submitted an annotation file that was generated with GFF2MSS and received feedback below.

```
5）
5-1：
assembly_gapにて、下記例の様に1 bpが指定されている場合がございました。
またestimated_lengthでknownが指定されておりました。
例
assembly_gap    1210523    estimated_length    known

assembly_gapはsequencing gapを記載するfeatureとなっておりますが、
1 bpのassembly_gapは、どの様な理由で記載を頂いておりますでしょうか。
塩基配列が決定できなかったnのlocationを、assembly_gapにて指定されて
おりますでしょうか。その場合は、指定不要となります。

5-2：
範囲指定をして頂いているassembly_gapではestimated_lengthでknownが
指定されておりますが、location範囲は一律100 bpとなっておりました。
sequencing gap領域において推定配列長不明であり、一律100 bpのnを
挿入をされている場合は、estimated_lengthではunknownの指定を
御願いします。配列中のnの挿入操作については、下記ページを
御参照ください。
https://www.ddbj.nig.ac.jp/ddbj/file-format.html#assembly_gap__Sequencing_Gap_Region_%E3%81%AE%E6%9B%B8%E5%BC%8F
```

To account for these comments, I introduced new options `--mag <minimum size of gap_assembly>` and `--gel <gap_assembly size known/unknown>` in a forked repo https://github.com/kfuku52/GFF2MSS/commit/ae6bda84a20de40731807dceceb22c3cb1928daf. The default behavior is unchanged.

If you are willing to incorporate this feature into your repo, I will gladly create a PR.

**Comment by maedat** [comment]
Thank you so much for taking the time to review my program and provide such valuable feedback.
 I truly appreciate your input and I am glad to hear that you have identified an opportunity to further improve it.

Based on your comment, I think that the modifications you made to GFF2MSS would be a great addition to the program. I am happy to accept your pull request and incorporate this feature into the repository.

**Comment by kfuku52** [comment]
I'm glad you like this feature! Could you share your thought on the other potential updates I suggested?

**Comment by maedat** [comment]
I would be more than happy to get your pull request for these three updates ("source", locus_tag, and CDS) !  Thank you!
