### ISSUE TITLE
ModuleNotFoundError: No module named 'Bio'

### ISSUE THREAD

**Issue by emmannaemeka** [maedat/GFF2MSS#9]
Hi,
I am trying to use this program to submit a genome annotation to DDBJ. I have some issues I will like to solve
1. I have a gff file with over 40000 features, is there an automated way to generate the anno.txt file?

2.  I encountered this problem running the program

Traceback (most recent call last):
  File "./GFF2MSS.py", line 23, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

**Comment by maedat** [comment]
Thank you for your interest in my script. 

I have been able to create an annotation file for DDBJ registration from the GFF that contains 2000-70000 genetic information. 

About your second question,  the following site may be of help regarding the errors you have encountered: https://stackoverflow.com/questions/49848517/biopython-no-module-named-bio

Please feel free to contact me if you have any questions.
